name: 'build package'

on:
  push:
    tags:
      - '*'

env:
  DOCKER_VERSION: 20.10.8

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - id: hash
        if: "startsWith(github.ref, 'refs/tags/v')"
        run: |
          echo ::set-output name=tag::${GITHUB_REF#refs/tags/v}

      - name: Set up Docker Buildx
        id:   buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          build-args: |
            RUNNER_VERSION=${{ steps.hash.outputs.tag }}
            DOCKER_VERSION=${{ env.DOCKER_VERSION }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ steps.hash.outputs.tag }}
